spring:
  application:
    name: crm-auth-service
  clean-on-startup: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  cache:
    type: redis
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET:changeMeInProductionThisIsAVeryLongSecretKey123456789}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

app:
  super-admin:
    email: ${SUPER_ADMIN_EMAIL:admin@crm.com}
    password: ${SUPER_ADMIN_PASSWORD:SuperAdmin123!}
    first-name: ${SUPER_ADMIN_FIRSTNAME:Super}
    last-name: ${SUPER_ADMIN_LASTNAME:Admin}

logging:
  level:
    root: INFO
    com.crm.AuthService: INFO
management:
  endpoint:
    web:
      exposure:
        include: health , info , metrics
    health:
      show-details: always
flyway:
  sql-migration-prefix: V
  repeatable-sql-migration-prefix: R
  clean-disabled: false  # Allow Flyway clean command
  clean-on-validation-error: true  # Clean on validation errors
  baseline-on-migrate: true


